# Generated by Django 5.0.1 on 2024-03-27 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 8, 39, 24, 273905)),
        ),
    ]
