# Generated by Django 5.0.1 on 2024-03-27 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_address_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 16, 8, 48, 576993)),
        ),
    ]
