# Generated by Django 5.0.1 on 2024-03-29 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_address_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 29, 15, 50, 0, 268012)),
        ),
    ]
